### PR TITLE
Setting priorities of todo items

### PR DESCRIPTION
**Pull request by okanvurdu**
Adding priority to tasks was implemented to `todo.py`. Also the tasks listed after sorted by priority as descending. I think, it's time to go **0.0.2@alpha** :blush:

### CODE REVIEW

**Comment by hmert** [comment]
awesome :clap:

**Comment by hmert** [comment]
I'll create a branch `0.0.2@alpha` :)

**Comment by okanvurdu** [comment]
Thanks for merging, I enjoyed a lot to contributing :)

**Comment by hmert** [comment]
Great! do not hesitate to send PR anytime :)

**Comment by okanvurdu** [comment]
Thanks again, I will send PRs in later times if I find something new :)

**Pull request merged**
