### PR TITLE
Propose man page #6

### PR DESCRIPTION
**Pull request by williamjmorenor**

### CODE REVIEW

**Comment by williamjmorenor** [comment]
captura de pantalla de 2015-07-15 22-49-39

**Comment by williamjmorenor** [comment]
I want to propose a base manpage and also I want to ask about to mark a release if the manpage is added, this way I will can update the package in Fedora

**Comment by hmert** [comment]
Hi @williamjmorenor , I'll merge your PR. Is it enough for you?

**Comment by williamjmorenor** [comment]
Can you create a release please?

https://help.github.com/articles/creating-releases/

**Comment by hmert** [comment]
done.

**Pull request merged**
